[Icon Theme]
Name=Breeze fallback
Comment=Fallback icons for non freedesktop environments

Directories=actions/16,actions/22,actions/32,actions/48

[actions/16]
Size=16
Context=Actions
Type=Scalable
MinSize=16
MaxSize=256

[actions/22]
Size=22
Context=Actions
Type=Scalable
MinSize=22
MaxSize=256

[actions/32]
Size=32
Context=Actions
Type=Scalable
MinSize=32
MaxSize=256

[actions/48]
Size=48
Context=Actions
Type=Scalable
MinSize=48
MaxSize=256
